import { v4 as uuid } from "uuid";

export default [
  {
    id: uuid(),
    name: "Apple cake",
    price: 12.5,
    quantity: 2,
    total: 25,
    comment: "Don't add apple",
  },
  {
    id: uuid(),
    name: "Banana cake",
    price: 13.5,
    quantity: 2,
    total: 26,
    comment: "Don't add Banana",
  },
  {
    id: uuid(),
    name: "Water cake",
    price: 14.5,
    quantity: 1,
    total: 14.5,
    comment: "Don't add Water",
  },
  {
    id: uuid(),
    name: "Apple cake",
    price: 12.5,
    quantity: 2,
    total: 25,
    comment: "Don't add apple",
  },
  {
    id: uuid(),
    name: "Apple cake",
    price: 12.5,
    quantity: 2,
    total: 25,
    comment: "Don't add apple",
  },
  {
    id: uuid(),
    name: "Apple cake",
    price: 12.5,
    quantity: 2,
    total: 25,
    comment: "Don't add apple",
  },
  {
    id: uuid(),
    name: "Apple cake",
    price: 12.5,
    quantity: 2,
    total: 25,
    comment: "Don't add apple",
  },
];
