import { v4 as uuid } from "uuid";

export default [
  {
    id: uuid(),
    product: "Apple cake",
    price: 15.5,
    startQuantity: 13,
    soldQuantity: 12,
    trashQuantity: 1,
    foodCost: 7,
  },
  {
    id: uuid(),
    product: "Banana cake",
    price: 12.5,
    startQuantity: 13,
    soldQuantity: 12,
    trashQuantity: 1,
    foodCost: 7,
  },
  {
    id: uuid(),
    product: "Water cake",
    price: 13.5,
    startQuantity: 13,
    soldQuantity: 12,
    trashQuantity: 1,
    foodCost: 7,
  },
  {
    id: uuid(),
    product: "Meat cake",
    price: 12.5,
    startQuantity: 13,
    soldQuantity: 12,
    trashQuantity: 1,
    foodCost: 7,
  },
  {
    id: uuid(),
    product: "Cloud cake",
    price: 12.5,
    startQuantity: 13,
    soldQuantity: 12,
    trashQuantity: 1,
    foodCost: 7,
  },
  {
    id: uuid(),
    product: "Tree cake",
    price: 10.5,
    startQuantity: 13,
    soldQuantity: 12,
    trashQuantity: 1,
    foodCost: 7,
  },
  {
    id: uuid(),
    product: "Paper cake",
    price: 122.5,
    startQuantity: 13,
    soldQuantity: 12,
    trashQuantity: 1,
    foodCost: 7,
  },
  {
    id: uuid(),
    product: "Mouse cake",
    price: 123.5,
    startQuantity: 13,
    soldQuantity: 12,
    trashQuantity: 1,
    foodCost: 7,
  },
];
