import { v4 as uuid } from "uuid";

export default [
  {
    id: uuid(),
    name: "Apple cake",
    weight: 2,
    price: 12.5,
    costItem: 2,
    costRecipe: 25,
  },
  {
    id: uuid(),
    name: "Banana cake",
    weight: 3,
    price: 112.5,
    costItem: 21,
    costRecipe: 123,
  },
  {
    id: uuid(),
    name: "Apple cake",
    weight: 2,
    price: 12.5,
    costItem: 2,
    costRecipe: 25,
  },
  {
    id: uuid(),
    name: "Apple cake",
    weight: 2,
    price: 12.5,
    costItem: 2,
    costRecipe: 25,
  },
  {
    id: uuid(),
    name: "Apple cake",
    weight: 2,
    price: 12.5,
    costItem: 2,
    costRecipe: 25,
  },
  {
    id: uuid(),
    name: "Apple cake",
    weight: 2,
    price: 12.5,
    costItem: 2,
    costRecipe: 25,
  },
  {
    id: uuid(),
    name: "Apple cake",
    weight: 2,
    price: 12.5,
    costItem: 2,
    costRecipe: 25,
  },
];
